POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Javascript course",
    "slug": "create-candle-1",
    "type": "post",
    "status": "published",
    "content": "First you need to eat some water...",
    "featuredImageUrl": "https://google.com",
    //"tags": ["cooking", "candle"],
    "metaOptions": {
        "metaValue": "{\"carEnasbled\":true,\"footerfdfasActive\":false}"
    },
    "authorId": 1,
    "tags": [1,2]
}